# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50cc70dcdaf77d58c7e14bf5b903840be7c3d0c52ef5a2eb95e86d72c0165345dffad2a22ae55ee9fb13a8e1811dd57955c9f294d4d8cc0728c48651601a1ef5

test:
  secret_key_base: 316792fc4bde9a889c72ecc409c2fc3208e639e69d99b113a76102a9b6a46951dee5c3694724eea0ac08c46520d641d72c79f80b7f125ceffd516a0811272736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
